spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8
    username: root
    password: alsm
    driver-class-name: com.mysql.jdbc.Driver


  ## Redis 配置
  ## Redis数据库索引（默认为0）
  redis:
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: -1
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 50
        ## 连接池中的最小空闲连接
        min-idle: 0
        ## 连接超时时间（毫秒）
    timeout: 0

  ##mail配置
  mail:
    host: smtp.163.com
    username: guochaojava@163.com
    password: xxxxxxxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.example.guochaojava.model
  mapperLocations: classpath:mapper/*.xml

#guochaojava 配置
guochaojava:
  redis:
    expire: 1800
  cookie:
    domain: localhost
  jwt:
    key: guochao@2018!
    #jwt token 有效时长（毫秒）
    exp: 1800000
  wechat:
    appid: appid
    appsecret: appsecret
  upload:
      windows: E://upload
      linux: /home/upload

logging:
  config: classpath:log4j2-online.xml